#!/usr/bin/env stack
-- stack script --resolver lts-13.26

{-
Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.

Answer: 4613732
-}

module Main where

main :: IO ()
main = print $ solution 4000000

fibs :: [Int]
fibs = 1 : 2 : zipWith (+) fibs (tail fibs)

solution :: Int -> Int
solution n = sum
           $ filter even
           $ takeWhile (< n) fibs
