#|
Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
|#

#lang racket

(define (get-fibs cap [fibs (list 1 2)])

  (define new-value (apply + (take (reverse fibs) 2)))

  (if (new-value . > . cap)
      fibs
      (get-fibs cap (append fibs (list new-value)))))

(apply + (filter even? (get-fibs 4000000)))
