"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

def fib(n):
     a, b = 1, 2
     for i in range(n):
         a,b=b,a+b
     return(a)

def euler(n):
     i = s = 0
     while(fib(i)<n):
         if(fib(i)%2==0):
             s = s + fib(i)
         i=i+1
     return(s)
	
print(euler(4000000))

# answer: 4613732 (ok)