# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
#
#     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.

use 5.025;
use strict;
use warnings;

use subs 'fib_seq_until', 'sum_even';

my $cap = 4_000_000;
say sum_even fib_seq_until $cap;

sub fib_seq_until {
    my ($cap) = @_;

    sub next_fib {
        my @fibs = @_;
        return $fibs[-1] + $fibs[-2];
    }

    my @fibs = (1, 2);
    my $new_fib = next_fib @fibs;

    while($new_fib < $cap) {
        push(@fibs, $new_fib);
        $new_fib = next_fib @fibs;
    }

    return @fibs;
}

sub sum_even {
    my $sum = 0;
    foreach my $el (@_) {
        if($el%2 == 0) {
            $sum += $el;
        }
    }

    return $sum;
}
