--[[
Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
]]

function Fib(N)
     A, B = 1, 2
     for I = 1, N do
         A, B = B, A + B
     end
     return(A)
end

function Euler(N)
     I, S = 0, 0
     while Fib(I) < N do
         if Fib(I)%2 == 0 then
             S = S + Fib(I)
         end
         I = I + 1
     end
     return(S)
end

print(Euler(4000000))

-- answer: 4613732 (ok)

--[[
Failed to improve the code with a diferent definition for Euler(N):

function Euler(N)
     S = 0
     for I = 1, N do
         if Fib(I)%2 == 0 then
             S = S + Fib(I)
         end
     end
     return(S)
end

 the problem lies in the for loop, since it's not I the variable, but Fib(I)
]]
