/*
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 * 
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not
 * exceed four million, find the sum of the even-valued terms.
 */

let answer = 4613732

func fibs(_ cap: Int) -> [Int] {
    var fibList = [1, 2]

    while fibList.last! < cap {
        fibList.append(
            fibList[fibList.count - 2 ... fibList.count - 1].reduce(0, +)
        )
    }

    return fibList
}

func main() {
    let sum = fibs(4_000_000).filter{ $0.isMultiple(of: 2) }.reduce(0, +)

    print((sum == answer ? "[ok]" : "[fail]") + " got \(sum)")
}

main()
